- name: Get Switch Inventory
  hosts: CTC
  gather_facts: no
  vars:
    switches: []
    visited: []

  tasks:


    - name: Clear CSV output
      file:
        path: ./output/switch_inventory.csv
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Build CSV headers
      lineinfile:
        dest: "./output/switch_inventory.csv"
        line: Banner,Store,Hostname,IP Address,Model,Serial Number,Stacked Number,Stacked Serial Number,Connection,Error Message
        create: true
        state: present
      delegate_to: localhost
      run_once: true

    - name: Clear error log
      file:
        path: ./error.log
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Clear updated hosts
      file:
        path: ./inventory/updated_hosts
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Build updated hosts
      lineinfile:
        dest: "./inventory/updated_hosts"
        line: "{{item}}"
        create: true
        state: present
      with_items:
        - '[CTC:children]'
        - 'FGL'
        - 'Franchise'
        - 'Marks'
        - '[FGL]'
        - '[Franchise]'
        - '[Marks]'
      delegate_to: localhost
      run_once: true

    - name: Start scanning
      set_fact:
        counter: 0
        
    - name: Start switch crawler
      include_tasks: crawler.yaml
      vars:
        ansible_hostname: "{{ inventory_hostname }}"
         
    - name: print visited
      debug:
        msg: "{{visited}}"
      
    - name: print switches
      debug:
        msg: "{{switches}}"


    # - name: Build CSV headers
    #   lineinfile:
    #     dest: "./output/switch_inventory.csv"
    #     line: Banner,Store,Hostname,IP Address,Model,Serial Number,Stacked Number,Stacked Serial Number,Connection,Error Message
    #     create: true
    #     state: present
    #   delegate_to: localhost
    #   run_once: true

    # - name: Generate CSV output
    #   lineinfile:
    #     dest: "./output/switch_inventory.csv"
    #     line: "{{group_names[-1] }},{{ item.store }},{{ item.hostname }},{{ item.ip }},{{ item.model }},{{ item.serialnumber }},{{ item.stackednumber }},{{ item.stackedserialnum | regex_replace(',', ' ') | regex_replace('u', '') }},{{ item.connection }},{{ item.errormsg }}"
    #     state: present
    #   loop: "{{ switches }}"
    #   delegate_to: localhost

    # - name: Build updated hosts
    #   lineinfile:
    #     dest: "./inventory/updated_hosts"
    #     line: "{{item}}"
    #     create: true
    #     state: present
    #   with_items:
    #     - '[CTC:children]'
    #     - 'FGL'
    #     - 'Franchise'
    #     - 'Marks'
    #     - '[FGL]'
    #     - '[Franchise]'
    #     - '[Marks]'
    #   delegate_to: localhost
    #   run_once: true

    # - name: Generate updated hosts
    #   lineinfile:
    #     dest: "./inventory/updated_hosts"
    #     line: "{{ item.hostname }}    ansible_host={{ item.ip }}"
    #     state: present
    #     insertafter: '^\[{{group_names[-1] }}\]'
    #   when:
    #     - item.connection == "success"
    #   loop: "{{ switches }}"
    #   delegate_to: localhost